DROP TABLE num_pedido;
DROP TABLE incidencias;
DROP TABLE tickets;
DROP TABLE lin_ped;
DROP TABLE pedidos;
DROP TABLE clientes;
DROP TABLE ing_pro;
DROP TABLE ingredientes;
DROP TABLE combos;   
DROP TABLE productos;
DROP TABLE subfamilia_producto;
DROP TABLE familia_producto;
DROP TABLE horario;
DROP TABLE repartidores;
DROP TABLE encargados;
DROP TABLE trabajadores;
DROP TABLE paginas_admin;

CREATE TABLE `trabajadores` (
  `COD_TRA` VARCHAR(20) NOT NULL,
  `DNI` VARCHAR(8) NOT NULL,
  `NOMBRE` VARCHAR(20) NOT NULL,
  `APELLIDOS` VARCHAR(45) NOT NULL,
  `NACIONALIDAD` VARCHAR(20) NOT NULL,
  `TELEFONO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`COD_TRA`));
  

CREATE TABLE `encargados` (
  `COD_TRA` VARCHAR(20) NOT NULL,
  `PASS` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`COD_TRA`),
  CONSTRAINT `COD_TRA`
    FOREIGN KEY (`COD_TRA`)
    REFERENCES `trabajadores` (`COD_TRA`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


CREATE TABLE `repartidores` (
  `COD_TRA` VARCHAR(20) NOT NULL,
  `DISPONIBLE` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`COD_TRA`),
  CONSTRAINT `FK_COD_TRA_REP`
    FOREIGN KEY (`COD_TRA`)
    REFERENCES `trabajadores` (`COD_TRA`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


CREATE TABLE `horario` (
  `NUM_HOR` INT NOT NULL AUTO_INCREMENT,
  `COD_TRA` VARCHAR(20) NOT NULL,
  `HORA_INI` DATE NOT NULL,
  `HORA_FIN` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`NUM_HOR`),
  INDEX `FK_HORARIO_COD_REP_idx` (`COD_TRA` ASC),
  CONSTRAINT `FK_HORARIO_COD_REP`
    FOREIGN KEY (`COD_TRA`)
    REFERENCES `repartidores` (`COD_TRA`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


CREATE TABLE `familia_producto` (
  `COD_FAM` VARCHAR(20) NOT NULL,
  `NOM_FAM` VARCHAR(20) NOT NULL,
  `POSICION` INT NOT NULL, 
  PRIMARY KEY (`COD_FAM`));


CREATE TABLE `subfamilia_producto` (
  `COD_SUB` VARCHAR(20) NOT NULL,
  `COD_FAM` VARCHAR(20) NOT NULL,
  `NOM_SUB` VARCHAR(45) NOT NULL,
  `IMG_SUB` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`COD_SUB`),
  INDEX `FK_COD_SUB_FAM_idx` (`COD_FAM` ASC),
  CONSTRAINT `FK_COD_SUB_FAM`
    FOREIGN KEY (`COD_FAM`)
    REFERENCES `familia_producto` (`COD_FAM`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


CREATE TABLE `productos` (
  `COD_PRO` VARCHAR(20) NOT NULL,
  `COD_SUB` VARCHAR(20) NOT NULL,
  `NOMBRE` VARCHAR(30) NOT NULL,
  `PRECIO` DECIMAL(6,2) NOT NULL,
  `DESCRIPCION` VARCHAR(145) NOT NULL,
  `URL_FOTO` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`COD_PRO`),
  INDEX `FK_COD_SUB_idx` (`COD_SUB` ASC),
  CONSTRAINT `FK_COD_SUB`
    FOREIGN KEY (`COD_SUB`)
    REFERENCES `subfamilia_producto` (`COD_SUB`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

 
CREATE TABLE `combos` (
  `COD_COM` VARCHAR(20) NOT NULL,
  `COD_PRO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`COD_COM`, `COD_PRO`),
  INDEX `FK_COD_PRO_2_idx` (`COD_PRO` ASC),
  CONSTRAINT `FK_COD_PRO_1`
    FOREIGN KEY (`COD_COM`)
    REFERENCES `productos` (`COD_PRO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_COD_PRO_2`
    FOREIGN KEY (`COD_PRO`)
    REFERENCES `productos` (`COD_PRO`),
	CONSTRAINT `COD_COM_IGUAL_COD_PRO_1`
	CHECK(`COD_COM` NOT LIKE`COD_PRO`)
);


CREATE TABLE `ingredientes` (
  `COD_ING` VARCHAR(20) NOT NULL,
  `NOMBRE` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`COD_ING`));


CREATE TABLE `ing_pro` (
  `COD_ING` VARCHAR(20) NOT NULL,
  `COD_PRO` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`COD_ING`, `COD_PRO`),
  INDEX `FK_COD_PRO_idx` (`COD_PRO` ASC),
  CONSTRAINT `FK_COD_PRO`
    FOREIGN KEY (`COD_PRO`)
    REFERENCES `productos` (`COD_PRO`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_COD_ING`
    FOREIGN KEY (`COD_ING`)
    REFERENCES `ingredientes` (`COD_ING`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);
    

CREATE TABLE `clientes` (
  `NOM_USER` VARCHAR(20) NOT NULL,
  `PASS` VARCHAR(20) NOT NULL,
  `NOMBRE` VARCHAR(20) NOT NULL,
  `APELLIDOS` VARCHAR(45) NOT NULL,
  `DIRECCION` VARCHAR(145) NOT NULL,
  `NUMERO` VARCHAR(3) NOT NULL,
  `PISO` VARCHAR(2) NOT NULL,
  `LETRA` VARCHAR(2) NULL,
  `ESCALERA` VARCHAR(9) NULL,
  `COD_POSTAL` VARCHAR(5) NOT NULL,
  `TELEFONO` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`NOM_USER`));

CREATE TABLE `pedidos` (
  `COD_PED` INT NOT NULL,
  `NOM_USER` VARCHAR(20) NOT NULL,
  `DIA_HORA` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`COD_PED`),
  CONSTRAINT `FK_NOM_USER`
    FOREIGN KEY (`NOM_USER`)
    REFERENCES `clientes` (`NOM_USER`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE TABLE `lin_ped` (
  `COD_PED` INT NOT NULL,
  `COD_PRO` VARCHAR(45) NOT NULL,
  `CANTIDAD` INT NOT NULL,
  `PRECIO_UNI` DECIMAL(6,2) NOT NULL,
  `CANTIDAD_PERDIDA` INT,
  `PRECIO_UNI_PERDIDO` DECIMAL(6,2),
  PRIMARY KEY (`COD_PED`, `COD_PRO`),
  INDEX `FK_COD_PRO_idx` (`COD_PRO` ASC),
  CONSTRAINT `FK_COD_PED_LP`
    FOREIGN KEY (`COD_PED`)
    REFERENCES `pedidos` (`COD_PED`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_COD_PRO_LP`
    FOREIGN KEY (`COD_PRO`)
    REFERENCES `productos` (`COD_PRO`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

  
CREATE TABLE `tickets` (
  `COD_TIC` INT NOT NULL,
  `COD_ENC` VARCHAR(20) NOT NULL,
  `COD_REP` VARCHAR(20) NOT NULL,
  `HORA_SALIDA` VARCHAR(20) NOT NULL,
  `HORA_LLEGADA` VARCHAR(20),
  PRIMARY KEY (`COD_TIC`),
  CONSTRAINT `FK_COD_PED`
    FOREIGN KEY (`COD_TIC`)
    REFERENCES `pedidos` (`COD_PED`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_COD_ENC`
    FOREIGN KEY (`COD_ENC`)
    REFERENCES `encargados` (`COD_TRA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_COD_REP`
    FOREIGN KEY (`COD_REP`)
    REFERENCES `repartidores` (`COD_TRA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE TABLE `incidencias` (
  `COD_INC` INT(10) NOT NULL AUTO_INCREMENT,
  `COD_TIC` INT NOT NULL,
  `DESCRIPCION` VARCHAR(300) NOT NULL DEFAULT '',
  PRIMARY KEY (`COD_INC`),
  INDEX `FK_COD_TICKET_idx` (`COD_TIC` ASC),
  CONSTRAINT `FK_COD_TICKET`
    FOREIGN KEY (`COD_TIC`)
    REFERENCES `tickets` (`COD_TIC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
    
CREATE TABLE `num_pedido` (
  `NUM_PEDIDO` VARCHAR(1) NOT NULL,
	`NUM_PED` INT NOT NULL,
  PRIMARY KEY (`NUM_PEDIDO`))
;

CREATE TABLE `paginas_admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `orden` INT,
  `opcion` VARCHAR(45) NOT NULL,
  `path` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));
